version: "3"

services:

  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: /bin/bash -c
    command: [ 'yarn dev' ]
    environment:
      APP_HOST: '0.0.0.0'
      APP_PORT: '5000'
      APP_LIVERELOAD_PORT: '5001'
    ports:
      - "5000:5000"
      - "5001:5001"
