version: "3"

services:

  app:
    image: node:17
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    entrypoint: yarn dev
    environment:
      APP_HOST: '0.0.0.0'
      APP_PORT: '5000'
    ports:
      - "5000:5000"
