# https://taskfile.dev

version: '3'

tasks:

  default:
    cmds: [ task: up ]

  up:
    cmds:
      - docker compose up -d

  exec:
    interactive: true
    cmds:
    - docker compose exec app bash
    