name: Deploy to GH Pages
on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy:
    name: Build and deploy
    environment:
      name: github-pages
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'

      - name: Install dependancies
        run: yarn install --frozen-lockfile

      - name: Build static files
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
